# Generated by Django 5.2.7 on 2025-11-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provenresult',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
