# Generated by Django 5.2.7 on 2025-11-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_provenresult_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='favicon',
        ),
        migrations.AddField(
            model_name='service',
            name='icon_class',
            field=models.CharField(blank=True, help_text="e.g. 'fa-solid fa-gear' or 'bi-gear'", max_length=120),
        ),
        migrations.AddField(
            model_name='service',
            name='icon_svg',
            field=models.TextField(blank=True, help_text='Paste inline SVG markup starting with <svg …>'),
        ),
    ]
