# Generated by Django 5.2.7 on 2025-11-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_service_favicon_service_icon_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon_class',
            field=models.CharField(blank=True, help_text="e.g. 'fa-solid fa-gear' or 'bi-gear'", max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon_svg',
            field=models.TextField(blank=True, help_text='Paste inline SVG markup starting with <svg …>', null=True),
        ),
    ]
