# Generated by Django 5.2.7 on 2025-11-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_service_icon_class_alter_service_icon_svg'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=150)),
                ('interest_service', models.CharField(blank=True, max_length=150)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'db_table': 'visitor_info',
            },
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='video',
            field=models.FileField(blank=True, help_text='MP4 recommended', null=True, upload_to='Contact/'),
        ),
    ]
