# Generated by Django 5.2.7 on 2025-11-04 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_visitorinfo_contactinfo_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
