# Generated by Django 5.2.7 on 2025-11-04 05:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_contactinfo_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='phone_number',
            field=models.BigIntegerField(blank=True, null=True, verbose_name=django.core.validators.MinValueValidator(0)),
        ),
    ]
