# Generated by Django 5.2.7 on 2025-11-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_contactinfo_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
