# Generated by Django 5.2.7 on 2025-11-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_contactinfo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provenresult',
            name='title',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
