# Generated by Django 5.2.7 on 2025-11-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_provenresult_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='phone_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
