# Generated by Django 5.2.7 on 2025-11-04 10:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_contactinfo_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsStatic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who_we_are_body', models.TextField()),
                ('mission_body', models.TextField()),
                ('vision_line', models.TextField()),
                ('cta_body', models.TextField()),
                ('stat_clients_percent', models.IntegerField(default=92)),
                ('stat_revenue_millions', models.IntegerField(default=50)),
                ('stat_businesses', models.IntegerField(default=100)),
                ('stat_years', models.IntegerField(default=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'About Us (Static Integers & Text)',
                'verbose_name_plural': 'About Us (Static Integers & Text)',
            },
        ),
        migrations.CreateModel(
            name='FaceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='faces/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('name', models.CharField(max_length=120)),
                ('position', models.CharField(blank=True, max_length=120)),
                ('is_founder', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-is_founder', 'name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_founder', True)), fields=('is_founder',), name='unique_true_founder_only')],
            },
        ),
    ]
