# Generated by Django 5.2.7 on 2025-11-04 10:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_aboutusstatic_facecompany'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutusstatic',
            name='cta_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AddField(
            model_name='aboutusstatic',
            name='hero_page',
            field=models.ImageField(default=1, upload_to='about/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutusstatic',
            name='mission_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AddConstraint(
            model_name='aboutusstatic',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='about_only_one_active'),
        ),
    ]
