# Generated by Django 5.2.7 on 2025-11-04 10:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_aboutusstatic_cta_image_aboutusstatic_hero_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutusstatic',
            name='above_state_image',
            field=models.ImageField(blank=True, null=True, upload_to='above_state_image/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
