# Generated by Django 5.2.7 on 2025-11-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_aboutusstatic_above_state_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='facecompany',
            name='consulting_engagements',
            field=models.PositiveIntegerField(blank=True, help_text='e.g. 75 (engagements)', null=True),
        ),
        migrations.AddField(
            model_name='facecompany',
            name='founder_year',
            field=models.PositiveIntegerField(blank=True, help_text='e.g. 25 (years of experience)', null=True),
        ),
    ]
