# Generated by Django 5.2.7 on 2025-11-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_facecompany_consulting_engagements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.ImageField(blank=True, help_text='Upload a square PNG/SVG (raster) for the service icon.', null=True, upload_to='service_icons/', verbose_name='Icon'),
        ),
    ]
