# Generated by Django 5.2.7 on 2025-11-10 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_service_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApproachSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField(help_text='Main heading above the section. Use plain text; <br> will be inserted on line breaks.')),
                ('image', models.ImageField(blank=True, help_text='Large left image.', null=True, upload_to='approach/')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Approach Section',
                'verbose_name_plural': 'Approach Sections',
            },
        ),
        migrations.CreateModel(
            name='ApproachStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('icon', models.ImageField(blank=True, help_text='Upload small square image for the step icon.', null=True, upload_to='approach/icons/')),
                ('icon_class', models.CharField(blank=True, help_text="e.g. 'fa-solid fa-bolt' or 'bi-lightning-charge'", max_length=120, null=True)),
                ('icon_svg', models.TextField(blank=True, help_text='Paste inline SVG markup starting with <svg …>', null=True)),
                ('title', models.CharField(max_length=80)),
                ('body', models.TextField(help_text='First paragraph.')),
                ('body_secondary', models.TextField(blank=True, help_text='Optional second paragraph.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.approachsection')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
