# Generated by Django 5.2.7 on 2025-11-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_approachsection_approachstep'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebanner',
            name='service_image',
            field=models.ImageField(blank=True, help_text='Upload a square PNG/SVG (raster) for the service icon.', null=True, upload_to='serice_image/', verbose_name='Service Image'),
        ),
    ]
