# Generated by Django 5.2.7 on 2025-11-11 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_homebanner_service_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('body_text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='transform/')),
                ('link', models.URLField(blank=True)),
                ('button_text', models.CharField(blank=True, default='Learn more', max_length=60)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='uniq_active_transform')],
            },
        ),
    ]
